require 'contentful/management'
require 'storage_room'
require 'pry'

STORAGEROOM_ACCOUNT_ID = '4d13574cba05613d25000004'
STORAGEROOM_APPLICATION_API_KEY = 'DZHpRbsJ7VgFXhybKWmT'

CONTENTFUL_ACCESS_TOKEN = 'access token'
CONTENTFUL_ORGANIZATION_ID = '1EQPR5IHrPx94UY4AViTYO'

StorageRoom.authenticate(STORAGEROOM_ACCOUNT_ID, STORAGEROOM_APPLICATION_API_KEY)

